version: '3.9'

services:
  postgres-dev:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=encryption
  postgres-prod:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - ./prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=prod_password
      - POSTGRES_USER=prod_user
      - POSTGRES_DB=encryption
