version: '3.9'

services:
  postgres-dev:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=****
      - POSTGRES_USER=****
      - POSTGRES_DB=****
  postgres-prod:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - ./prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=****
      - POSTGRES_USER=****
      - POSTGRES_DB=****
