name: Build and deploy artifact to repsy.io

on:
  workflow_call:

jobs:
  cipher-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to repsy.io Maven repository
        run: |
          ./gradlew publish -Prepo_user=$REPSY_LOGIN -Prepo_password=$REPSY_PASSWORD
        env:
          REPSY_LOGIN: ${{ secrets.REPSY_LOGIN }}
          REPSY_PASSWORD: ${{ secrets.REPSY_PASSWORD }}
