name: Build and deploy artifact to repsy.io

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cipher-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup build
        uses: gradle/gradle-build-action@v2

      - name: Publish to repsy.io Maven repository
        run: |
          ./gradlew publish -Prepo_user=$REPO_USER -Prepo_password=$REPO_PASSWORD
        env:
          REPO_LOGIN: ${{ secrets.REPSY_LOGIN }}
          REPO_PASSWORD: ${{ secrets.REPSY_PASSWORD }}
